### ISSUE TITLE
Error with QuickGraph

### ISSUE THREAD

**Issue by ignatandrei** [notanaverageman/Depso#1]
Hello
I have tried to see your project to add to my list of RSCG from https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

However, when compiling, the error message is 

1>D:\gth\RSCG_Examples\v2\rscg_examples\Depso\src\InjectDemo\Program.cs(9,22,9,39): error DEP000: Internal error while generating source code System.IO.FileNotFoundException: Could not load file or assembly 'QuickGraph.NETStandard, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Do I need to add the dependency ? I wish not, if it is necessary just for generating code ...

**Comment by ignatandrei** [comment]
Added the project for your convenience
[InjectDemo.zip](https://github.com/user-attachments/files/15848465/InjectDemo.zip)

**Comment by notanaverageman** [comment]
Thanks for reaching out. Version `1.0.0` had this bug and I had already released version `1.0.1` to fix this issue. I have deprecated and delisted the buggy version from NuGet so that it can't be referenced.

**Comment by ignatandrei** [comment]
Confirm it is ok
https://ignatandrei.github.io/RSCG_Examples/v2/docs/depso
